title: promoted.blue
description: Leading the conversation about feed monetisation on Bluesky
theme: just-the-docs

url: https://promoted.blue

include: [".well-known"]

aux_links:
  Visit us on Bluesky: https://bsky.app/profile/promoted.blue
